---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-2004
    image: "artifactory-medmuc.zeiss.org:8084/docker-public/geerlingguy/docker-ubuntu2004-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    tmpfs:
      - /sys/fs/cgroup
      - /run

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}"
    ANSIBLE_COLLECTIONS_PATHS: "${ANSIBLE_COLLECTIONS_PATHS}"
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint
...
